name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - name: Build
        run: make

      - uses: actions/upload-artifact@v7
        with:
          name: SaltyNX-Tool
          path: SaltyNX-Tool.nro
